### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by arthuryeti** [thomasforth/MS4Plugin#1]
Hi @thomasforth,

I'm willing to make the iOS support, do you have more information about that? How long it could take?

**Comment by thomasforth** [comment]
Hi Atu,

We have a very early version of the Moodstocks plugin working on iOS. I will try and finish it this week. If you could help with the beta testing that would be great.

Tom

**Comment by arthuryeti** [comment]
Awesome.

I would love to help ;)

**Comment by thomasforth** [comment]
Great news, the beta is ready -- I sent you an email.

We'll be live on Github within a week, hopefully much sooner.
