### ISSUE TITLE
Licence needed

### ISSUE THREAD

**Issue by mattvot** [thomasforth/MS4Plugin#2]
Hi Thomas,

Are you able to add a licence to the project? We would really like to use this plugin as it is recommended by Moodstocks (https://github.com/Moodstocks/moodstocks-phonegap-plugin) and works well. 

We are hesitant to implement this plugin as there is currently no document setting out the licence (e.g. MIT, BSD etc)

Thanks

**Comment by thomasforth** [comment]
Hi mattvot,

Great that the plugin works well! Thanks for reminding me about the license. I forgot.

Great news, the license is MIT -- as with the original Moodstocks plugin. I have updated the repository with a LICENSE file at its root.

Tom
