### ISSUE TITLE
File input no longer works

### ISSUE THREAD

**Issue by ddeklerk** [thomasforth/MS4Plugin#3]
When I add this plugin to my cordova app (Meteor) and try to select an image with an input element the menu to select an image comes up and all, but the input stays empty afterwards. This only happens on mobile and after that any input elements with the type of "file" are unusable.

To test if this plugin was really the problem I did the following:
- I made a new Meteor project
- I added the plugin with `meteor add cordova:com.moodstocks.phonegap@https://github.com/thomasforth/MS4Plugin/tarball/00d255d481be0e4577ed78ae68f6c1ae6f9ee83f`
- I copied a cordova override folder from a previous project which contains the files that need to be edited according to the installation instructions, and only those files
- I gave the project a name and id in the mobile config so the folder names would match with the override folder
- I added `<input type="file">` to the HTML

**Comment by thomasforth** [comment]
Thank you for the report.

Realistically I only have enough free time to test the plugin and to fix bugs that arise in a standard Phonegap install. The reliance on true-native (ie. pre-compiled C; not Java or Objective-C) code in the Moodstocks plugin means that we have to use some non-standard plugin development techniques which may be giving rise to this issue -- though I can't think why.

Hopefully someone else will see this report and be able to help. I will certainly merge any pull request that fixes it.

If solving this problem is critical to your product then don't hesitate to contact me by email.

**Comment by hzrbasaran** [comment]
Hi,
Do you have android studio installation video or documentation ?

**Comment by thomasforth** [comment]
Hello. Yes.

The Android installation video example is at https://www.youtube.com/watch?v=TgIBX6r1nl4

Let me know if there are any problems.

**Comment by hzrbasaran** [comment]
Hi
i have any problems.

08-13 16:12:40.081: E/AndroidRuntime(10174): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wdt.arproject/com.wdt.arproject.MainActivity}: android.view.InflateException: Binary XML file line #7: Class is not a View org.apache.cordova.CordovaWebView

**Comment by thomasforth** [comment]
Can you confirm that you are using Phonegap v3.1 in Eclipse with ADT and let me know if you're on a Mac, Windows, or Linux machine.

I know that v3.1 is an out of date Phonegap,but this is the best place to start debugging. We have the example working with much newer version of Phonegap.

If you have Phonegap v3.1 in Eclipse with ADT please try to follow the steps in the video again and check whether you get the same problems.

If there are still problems then I'll try to work with you to fix them but let's try and avoid any unnecessary work by being thorough at the start.

Good luck,

Tom

**Comment by hzrbasaran** [comment]
Thanks for answers.
I use cordova 5.1.1
CordovaFragment.java have any problems :(
R.layout.fragment_cordova is not a CordovaWebView and i cant.
thanks for answers again.

**Comment by thomasforth** [comment]
It sounds like you are using Android Studio also. Is that correct?

**Comment by hzrbasaran** [comment]
I'm trying all platforms. (Eclipse,Android Studio,Netbeans :) )
back to eclipse again. I'm going crazy
Do you have any suggestions

**Comment by thomasforth** [comment]
Okay. Probably the best way to continue is to focus.

Only Eclipse will work. I cannot support anything else. 

Please make sure that you have phonegap v3.1 installed. I cannot support anything else.

Can I suggest that as a first step you verify that you can create, build, and install a new phonegap v3.1 project on a device. If you can do that you're 80% of the way towards getting Moodstocks working.

**Comment by hzrbasaran** [comment]
I cant use phonegap v3.1. my project ionic angular framework. IOS version very good, but android disaster. I have to find another plugin
