### ISSUE TITLE
Fully-offline bundles for iOS

### ISSUE THREAD

**Issue by mattvot** [thomasforth/MS4Plugin#4]
Hey,

> We have not yet implemented fully-offline bundles for iOS. This is coming soon and we foresee no difficulties. If you need this now, please get in touch.

Is this still the case? We may be looking to use this in the coming months,

Thanks

**Comment by thomasforth** [comment]
Hey,

We haven't implemented fully-offline bundles for iOS yet, but you've reminded me that we should. We'll work on this tomorrow and let you know how we progress. I don't think it will be difficult at all. Will be great if, once we've done it, you can test it out for us. :)

Tom

**Comment by mattvot** [comment]
Awesome, thanks!

**Comment by mattvot** [comment]
Hmmm, accidentally closed this...

**Comment by thomasforth** [comment]
As always, it took longer than we hoped, but this is now done. We are testing internally (should take a couple of hours) but I expect it will work. Please re-open this issue if there are any problems.
