### ISSUE TITLE
Full screen scanner container issue on larger resolutions

### ISSUE THREAD

**Issue by Craigstock** [thomasforth/MS4Plugin#5]
Hi,

After installing the plugin, the scanner preview container is full screen on a smaller iPhone 5, however on the iPhone 6 the scanner preview page has white blocks on the right side and bottom. Is there a way to fix this? 

I have checked through the CSS, HTML, JS etc, but cant seem to find a way to set the preview full screen.

![cab3d84a-e8f8-44ea-9fac-af49c41b0874](https://cloud.githubusercontent.com/assets/13197185/10133796/a5761236-65e0-11e5-966a-bbabe2b7b8e9.PNG)

**Comment by thomasforth** [comment]
I am almost certain that this a bug in our code and will need fixing by us. We'll investigate today and you should expect a fix by the middle of next week at the latest and hopefully much sooner.

Best,

Tom

**Comment by Craigstock** [comment]
Thanks Tom, much appreciated!

**Comment by thomasforth** [comment]
Hi Craigstock,

I've just updated the ScannerViewController.xib file. Can you try updating the version in your current project and let me know if that fixes the problem,

Thanks,

Tom

**Comment by Craigstock** [comment]
Hi Tom,

Unfortunately having the same issue (see below):

![img_5384](https://cloud.githubusercontent.com/assets/13197185/10391652/97ea7172-6e80-11e5-9902-132b895639eb.PNG)

**Comment by thomasforth** [comment]
Just pushed another update to the ScannerViewController.xib file. Can you give that a try and see how it goes?

**Comment by jeoff09** [comment]
Hello guys ,

i just try the new version after your update, but it still not working on my project with the iPhone 6. The scanner preview stay in blocks on the right side and bottom.

Thanks 

Jeoffrey

**Comment by thomasforth** [comment]
Thanks all and sorry for the delay fixing this bug. iOS is hard sometimes but we'll get it soon.

**Comment by thomasforth** [comment]
Hi all, we've just tried to replicate this bug on an iPhone 6s running iOS 9 and we can't reproduce the problem.

We're using Phonegap v3.6, but I can't see how that would cause a problem. I'm beginning to wonder if this is a specific iPhone 6 bug so I'm asking the main Moodstocks team in Paris to investigate a bit.

**Comment by thomasforth** [comment]
Here's a project that we know works on our systems. Can anyone struggling with this bug please run it on their iOS device and confirm whether they still experience the same problem.

https://dl.dropboxusercontent.com/u/10939944/Moodstocks_iPhone6bus_Test.zip

**Comment by jeoff09** [comment]
hi ,

That work good on this project ! But not working on my project,  i think i have a problem on my application.

thanks for the correction 
Jeoffrey

**Comment by thomasforth** [comment]
I think that this bug has been fixed. If you disagree, please re-open this thread.

**Comment by Arcrueid** [comment]
i have the same problem u.u
