### ISSUE TITLE
iPad full screen scanning issue

### ISSUE THREAD

**Issue by masterg99** [thomasforth/MS4Plugin#7]
Hi,
So far i have the entire install working on IOS.

I had to edit the .xib to make the camera window full screen on the iPad. This works.
The problem i have now is that the camera is working full screen in portrait mode but the iPad is in landscape mode.

How can i make the camera work in landscape?

Thanks

**Comment by thomasforth** [comment]
Hi there,

Thanks for the bug report. Can you please clarify one thing for me. When you say "I had to edit the .xib..." do you mean that you updated it to the latest version on this repository? Or do you mean that you have added custom code?

We'll look at this as soon as possible,

Best,

Tom

**Comment by masterg99** [comment]
Hi,
Thanks for the quick reply!

I took the latest from github. 
I then looked at the other incident report with a simular problem.

Then in xcode, i edited: /resources/ScannerViewController.xib
Set size: iPad full screen
Orientation: Landscape

This works on the iPad as it views the camera full screen but the camera is still in portrait mode so the picture is side ways.

Ive attached a picture of the problem.

Cheers,
Mark

![20151016_130229](https://cloud.githubusercontent.com/assets/7642570/10541123/6923d5aa-7406-11e5-9755-21f67189a8c1.jpg)

**Comment by thomasforth** [comment]
Excellent. I can reproduce the bug on my end (we just use an iPod Touch) so we should have a fix soon.

Thanks for reporting this bug,

Tom

**Comment by thomasforth** [comment]
I just pushed a fix for this bug. Either start a new project or replace the ScannerViewController.m file with the new version and let me know if that works for you.

**Comment by masterg99** [comment]
Amazing! Worked like a charm.
Thank you
